### ISSUE TITLE
can  u change like this

### ISSUE THREAD

**Issue by iwin2471** [chowder985/SRSimulator#2]
https://github.com/chowder985/SRSimulator/blob/d912e3bfd1dd1ad88a1c5979b596d9333dc0fd46/login.html#L135

 var id = document.getElementById("idInput").value;
 var pass = document.getElementById("passInput").value;

        var form = document.createElement("form");
        var email = document.createElement("input");
        var Name = document.createElement("input");
        var pw = document.createElement("input");

        form.setAttribute("method", "post");
        form.setAttribute("action", "/auth/reg");

        email.setAttribute("name", "email");
        email.setAttribute("value", $('#iemail').val());

        Name.setAttribute("name", "name");
        Name.setAttribute("value", $('#Name').val());

        pw.setAttribute("name", "pw");
        pw.setAttribute("value", $('#pw').val());
        form.appendChild(email);
        form.appendChild(Name);
        form.appendChild(pw);
        form.submit();

**Comment by chowder985** [comment]
U mean i should get rid of the jquery code?

2017. 10. 30. 오후 1:56에 "Younjune Kim" <notifications@github.com>님이 작성:

**Comment by chowder985** [comment]
Sorry i meant the ajax code

2017. 10. 30. 오후 1:56에 "Younjune Kim" <notifications@github.com>님이 작성:

**Comment by iwin2471** [comment]
yeah
